# WIP
# Todo: check cmake, gcc, clangs versions.

# Use Ubuntu 14.04
sudo: required
dist: trusty

language: c
compiler:
  - clang
  - gcc

install:
   sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
   sudo apt-get update -qq;

 - if [ $CXX = "g++" ]; then
   sudo apt-get install -qq gcc-4.9 g++-4.9;
   fi;

# RAM: TODO: Ninja builds.
script:
  - mkdir build
  - cd build
  - cmake ../
  - make
