# WIP
# Todo: check cmake, gcc, clangs versions.

# Use Ubuntu 14.04
sudo: required
dist: trusty

language: c
compiler:
  - clang
  - gcc

# RAM: TODO: Ninja builds.
script:
  - mkdir build
  - cd build
  - cmake ../
  - make
