# WIP
# Todo: check cmake, gcc, clangs versions.

# Use Ubuntu 14.04
sudo: required
dist: trusty

language: c

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - ninja-build
      env: COMPILER=gcc-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - ninja-build
      env: COMPILER=clang-3.7

script:
  - mkdir build
  - cd build
  - CC=$COMPILER cmake ../ -G Ninja
  - ninja
