# WIP
# Todo: check cmake, gcc, clangs versions.

# Use Ubuntu 14.04
sudo: required
dist: trusty

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6

    packages:
    # install toolchains
    - gcc-5
    - g++-5
    - clang-3.6


language: c
compiler:
  - clang
  - gcc

install:
  - if [ $CXX = "g++" ]; then
    #sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
    #sudo apt-get update -qq;
    #sudo apt-get install -qq gcc-4.8 g++-4.8;
    sudo rm /usr/bin/g++;
    sudo rm /usr/bin/gcc;
    sudo ln -s /usr/bin/g++-5 /usr/bin/g++;
    sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc;
    fi;

#install:
#   sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
#   sudo apt-get update -qq;
#
# - if [ $CXX = "g++" ]; then
#   sudo apt-get install -qq gcc-4.9 g++-4.9;
#   fi;

# RAM: TODO: Ninja builds.
script:
  - mkdir build
  - cd build
  - cmake ../
  - make
