os: Visual Studio 2015
clone_folder: c:\projects\sewing
platform: x64
configuration: Release

matrix:
  - environment:
      VS_GENERATOR: "Visual Studio 14 2015 Win64"
    platform: x64
  - environment:
      VS_GENERATOR: "Visual Studio 14 2015"
    platform: x86


#environment:
  #matrix:
    #- VS_GENERATOR: "Visual Studio 14 2015 Win64"
    #- VS_GENERATOR: "Visual Studio 14 2015"

build:

build_script:
  - cmd: cd "c:\projects\sewing"
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake cmake -Dsewing_use_cxx_11=ON ../ -G"%VS_GENERATOR%"
  - cmd: msbuild /m /p:Configuration=Release sewing_test.sln
  - cmd: ctest --timeout 60
